SDL_Pango
SDL_gfx
perl-tree-dagnode
perl-Sub-Uplevel
perl-test-warn
perl-Test-Exception
perl-Algorithm-Diff
perl-Text-Diff
perl-Test-Differences
perl-Test-Tester
perl-Test-NoWarnings
perl-Test-Deep
perl-Devel-StackTrace
perl-Class-Data-Inheritable
perl-Exception-Class
perl-Test-Most
perl-Tie-Simple
perl-Archive-Zip
perl-Capture-Tiny
perl-Text-Patch
perl-Class-Inspector
perl-File-ShareDir
perl-Probe-Perl
perl-IPC-Run3
perl-Test-Script
perl-File-Which
perl-Alien-SDL
perl-SDL
perl-Locale-Maketext-Lexicon
perl-IPC-System-Simple
perl-File-Slurp
perl-Compress-Bzip2
frozen-bubble
