perl-Log-Message
perl-Log-Message-Simple
perl-Term-UI
perl-Term-ReadLine-Gnu
perl-Object-Accessor
perl-Module-Pluggable
perl-DBIx-Simple
perl-DBD-SQLite
perl-CPANPLUS-Dist-Build
perl-Archive-Extract
perl-CPANPLUS
